server:
  port: 2003

spring:
  datasource:
    url: jdbc:postgresql://172.18.0.1:5432/cch
    username: postgres
    password: 81524Rac
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_schema: public

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
