

spring:
  datasource:
    url: jdbc:postgresql://pg_container:5432/cch
    username: postgres
    password: 81524Rac
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: public
